services:
  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.redirect-router.entrypoints=web"
      - "traefik.http.routers.redirect-router.rule=Host(`redirect.localhost`)"
      - "traefik.http.routers.redirect-router.middlewares=redirect-regex"
      - "traefik.http.middlewares.redirect-regex.redirectRegex.regex=(.)*"
      - "traefik.http.middlewares.redirect-regex.redirectRegex.replacement=https://blog.jensknipper.de"
      - "traefik.http.middlewares.redirect-regex.redirectRegex.permanent=false"